"""add user role

Revision ID: da35035c39c8
Revises: b0a26d1ed72c
Create Date: 2025-01-26 19:36:02.086446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da35035c39c8'
down_revision: Union[str, None] = 'b0a26d1ed72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the Enum type
    user_role_enum = sa.Enum("USER", "ADMIN", name="user_role")
    user_role_enum.create(op.get_bind(), checkfirst=True)

    # Add the column using the Enum type
    op.add_column(
        "users",
        sa.Column("role", user_role_enum, nullable=False, server_default="USER"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column
    op.drop_column("users", "role")

    # Drop the Enum type
    user_role_enum = sa.Enum("USER", "ADMIN", name="user_role")
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
